network_type: MultilevelINN
name: "Ala_Multilevel_default"
training_type: "phase"
train_split: .7

training_params: {
  batch_size: 1024,
  num_workers: 0,

  optimizer: {
    name: "adam",
    lr: 3.e-5,
    weight_decay: 1.e-6,
    betas: [0.99, 0.999],
  },
  lr_scheduler: "onecyclelr",
  accelerator: "gpu",

  gradient_clip: 3.0,

  wavelet_loss: {
    reconstruction_code: 1.0,
  },
  detail_loss: {
    detail_ML: 1.0
  },
  coarse_loss: {
    coarse_ML: 1.0
  },

  wavelet_epochs: 20,
  detail_epochs: 10,
  coarse_epochs: 10,

  noise: 1.e-2,
}

network_params: {
  dims : [[66,], [33,], [16,]],
  verbose : False,
  min_hidden_channels: 64,
  max_hidden_channels: 256,
  min_hidden_width: 128,
  max_hidden_width: 512,
  blocks_per_unit: 3,
  max_depth: -1,
  permute_type: "hard",
  truncate_left: True,
  coupling_type: "all_in_one",
  max_fc_units: 1,
  initial_convolution: False,
}

trainer_kwargs: {
   overfit_batches: 1
 }
