molecule: "alanine_dipeptide"
network_name: "RNVPfwkl"


network_params: {
  inn_depth: 10,
  subnet_max_width: 2000,
  subnet_depth: 8,
  batch_size: 1000,
  max_epochs:  2000,
  optimizer: {
    name: "Adam",
    lr: 1.e-2,
  },
  lr_scheduler: "onecyclelr",
  latent_target_distribution: {
    name: "Normal",
    sigma: 1.,
  },
  gradient_clip: 5.0,
}

training_params: {
  train_split: .035  # 0 - .8
}

trainer_kwargs: {
#  overfit_batches: 1,
#  log_every_n_steps: 1,
}
