molecule: "/OppA/Peptides/1b5j"
network_name: "RNVPfwkl"

network_params: {
  inn_depth: 10,
  subnet_max_width: 2000,
  subnet_depth: 8,
  batch_size: 1000,
  max_epochs:  20000,
  optimizer: {
    name: "Adam",
    lr: 1.e-3,
  },
  lr_scheduler: "onecyclelr",
  latent_target_distribution: {
    name: "Normal",
    sigma: 1.,
  },
  gradient_clip: 10.0,
  model_checkpoint: {
    monitor: "auto",
    save_last: True,
    every_n_epochs: 25,
    save_top_k: 1,
  }

}

training_params: {
  train_split: .7  # 0 - .8
}

trainer_kwargs: {
#  overfit_batches: 1
}
