molecule: "/OppA/Peptides/1b5j"
network_name: "RNVPfwkl"

network_params: {
  inn_depth: 24,
  subnet_width: 512,
  batch_size: 1024,
  max_epochs:  20000,
  optimizer: "Adam",
  lr_scheduler: "onecyclelr",
  latent_target_distribution: {
    name: "Normal",
    sigma: 1.,
  },
  gradient_clip: 10.0,
}

training_params: {
  train_split: .7  # 0 - .8
}

trainer_kwargs: {
#  overfit_batches: 1
}
