molecule: "Dialanine"
network_name: "RNVPrvklLatent"

network_params: {
  inn_depth: 10,
  subnet_max_width: 256,
  subnet_depth: 8,
  batch_size: 1000,
  max_epochs:  200,
  optimizer: {
    name: "Adam",
    lr: 5.e-4,
  },
#  lr_scheduler: "onecyclelr",
  latent_target_distribution: {
    name: "Normal",
    sigma: 1.,
  },
  lambda_alignment: 1.,
  gradient_clip: 5.0,
  latent_network_params: {
    inn_depth: 3,
    subnet_max_width: 256,
    subnet_depth: 8,
    batch_size: 1000,
    max_epochs:  20,
    optimizer: {
      name: "Adam",
      lr: 1.e-3,
    },
    lr_scheduler: "onecyclelr",
    latent_target_distribution: {
      name: "Normal",
      sigma: 1.,
    },
    gradient_clip: 5.0,
  }
}

training_params: {
  train_split: .7  # 0 - .8
}

trainer_kwargs: {
  overfit_batches: 1
}
