molecule: "Dialanine"
network_name: "RNVPfwkl"


network_params: {
  inn_depth: 48,
  subnet_width: 256,
  batch_size: 1024,
  max_epochs:  1,
  optimizer: {
    name: "Adam",
    lr: 3.e-4,
  },
  lr_scheduler: "onecyclelr",
  latent_target_distribution: {
    name: "Normal",
    sigma: 1.,
  },
  gradient_clip: 10.0,
  track_grad_norm: 2,
}

training_params: {
  train_split: .7  # 0 - .8
}

trainer_kwargs: {
#  overfit_batches: 1,
  log_every_n_steps: 1,
}
