molecule: "Dialanine"
network_name: "RNVPfwkl"


network_params: {
  inn_depth: 24,
  subnet_max_width: 256,
  subnet_depth: 3,
  batch_size: 1000,
  max_epochs:  5,
  optimizer: {
    name: "Adam",
    lr: 3.e-5,
  },
#  lr_scheduler: "onecyclelr",
  latent_target_distribution: {
    name: "Normal",
    sigma: 1.,
  },
  gradient_clip: 10.0,
  track_grad_norm: 2,
}

training_params: {
  train_split: .7  # 0 - .8
}

trainer_kwargs: {
#  overfit_batches: 1,
#  log_every_n_steps: 1,
}
