network_name: "RNVPrvkl"

distribution_params: {
  means: [[0, 0], [0, 10]],
  stds: [[1, 1], [1, 1]],
  weights: [1, 1],
}

network_params: {
  inn_depth: 12,
  subnet_max_width: 256,
  subnet_growth_factor: 256,
  subnet_depth: 5,
  batch_size: 1024,
  max_epochs:  5,
  lr_scheduler: "onecyclelr",
  optimizer: {
    name: "Adam",
    lr: 1.e-3,
  },
  latent_target_distribution: {
    name: "Normal",
    sigma: 1.,
  },
  gradient_clip: 10.0,
}

training_params: {
  train_split: .7,
  redo_premodel: True,
  iterations: 100,
  scale: .01,
}

trainer_kwargs: {
#  overfit_batches: 1
}
