molecule: "/OppA/Peptides/1b4z"
network_name: "RNVPfwkl"

network_params: {
  inn_depth: 10,
  subnet_max_width: 2000,
  subnet_depth: 8,
  batch_size: 1000,
  max_epochs:  200,
  optimizer: {
    name: "Adam",
    lr: 3.e-5,
  },
  lr_scheduler: "onecyclelr",
  latent_target_distribution: {
    name: "Normal",
    sigma: 1.,
  },
  gradient_clip: 5.0,
  track_grad_norm: 2,
}

training_params: {
  train_split: .7  # 0 - .8
}

trainer_kwargs: {
#  overfit_batches: 1
}
