molecule: "/OppA/Peptides/1b4z"
network_name: "RNVPfwkl"


network_params: {
  inn_depth: 24,
  subnet_width: 256,
  batch_size: 1024,
  max_epochs:  2000,
  optimizer: {
    name: "Adam",
    lr: 3.e-5,
    betas: [.99, .9999],
  },
  latent_target_distribution: {
    name: "Normal",
    sigma: 1.,
  },
  gradient_clip: 10.0,
}

training_params: {
  train_split: .7  # 0 - .8
}

trainer_kwargs: {
#  overfit_batches: 1
}
